services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rooot
      POSTGRES_DB: crm2
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    container_name: crm
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:rooot@postgres:5432/crm2?schema=public
      PORT: 3030
      STUDENT_ACCESS_KEY: student_access_key
      STUDENT_REFRESH_KEY: student_refresh_key
      TEACHER_ACCESS_KEY: teacher_access_key
      TEACHER_REFRESH_KEY: teacher_refresh_key
      ADMIN_ACCESS_KEY: admin_access_key
      ADMIN_REFRESH_KEY: admin_refresh_key
      PARENT_ACCESS_KEY: parent_access_key
      PARENT_REFRESH_KEY: parent_refresh_key
      ACCESS_TOKEN_KEY: your_access_token_secret_key_here
      REFRESH_TOKEN_KEY: your_refresh_token_secret_key_here
      ACCESS_TIME: 10h
      REFRESH_TIME: 10d
      COOKIE_TIME: 86400000
      BCRYPT_ROUND: 7
    ports:
      - '3030:3030'
    command: ['npm', 'run', 'start']

volumes:
  postgres-data:
